distro: bionic
language: node_js
node_js:
  - 14
install:
  - sudo apt-get update
  - sudo apt-get install python3-pip python3-setuptools python3-wheel
  - python3 -m pip install --user pipenv
  - pipenv install --dev
script:
  - pipenv run ci
