service: enip-backend

custom:
  stage: ${opt:stage, 'staging'}
  pythonRequirements:
    dockerizePip: true
    slim: false # jsonschema package fails with true: https://github.com/Julian/jsonschema/issues/628#issuecomment-564456058
    useDownloadCache: false
    noDeploy: [
        'boto3',
        'botocore',
        'docutils',
        'jmespath',
        'python-dateutil',
        's3transfer',
        'six',
        'pip',
        'setuptools'
    ]

  datadog:
    forwarder: "${ssm:/shared/enip/datadog_forwarder_arn~true}"
    flushMetricsToLogs: true
    addLayers: true
    logLevel: 'INFO'
    enableDDTracing: true

  prune:
    automatic: true
    number: 3

provider:
  name: aws
  runtime: python3.7
  region: us-west-2
  vpc:
    subnetIds:
      - "${ssm:/vpc/subnets/private/id/0~true}"
      - "${ssm:/vpc/subnets/private/id/1~true}"
      - "${ssm:/vpc/subnets/private/id/2~true}"
    securityGroupIds:
      - "${ssm:/vpc/security-group/default/id~true}"
  tags:
    env: ${self:custom.stage}

  environment:
    SENTRY_DSN: ${ssm:/shared/enip/sentry_dsn~true}
    SENTRY_ENVIRONMENT: ${self:custom.stage}
    POSTGRES_URL: "${ssm:/${self:custom.stage}/enip/db/url~true}"
    POSTGRES_RO_URL: "${ssm:/${self:custom.stage}/enip/db/url_ro~true}"
    INGEST_TEST_DATA: "true"
    ELECTION_DATE: "2020-11-03"
    AP_API_KEY: ${ssm:/shared/enip/ap_api_key~true}
    S3_BUCKET: voteamerica-enip-data
    S3_PREFIX: ${self:custom.stage}

  memorySize: 3008
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: 'arn:aws:s3:::voteamerica-enip-data'
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: 'arn:aws:s3:::voteamerica-enip-data/*'

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-plugin-datadog

functions:
  run:
    handler: enip_backend.lambda_handlers.run
    # events:
    #   - schedule: "rate(5 minutes)"
    timeout: 290
    maximumRetryAttempts: 0

  run_states:
    handler: enip_backend.lambda_handlers.run_states
    # events:
    #   - schedule: "rate(15 minutes)"

    # Time out in a little less than 3 minutes so if we're overloaded we don't
    # end up stacking multiple invocations
    timeout: 890
    maximumRetryAttempts: 0



package:
  exclude:
    - 'node_modules/**'
    - '.vscode/**'
    - '.mypy_cache/**'
    - 'package.json'
    - 'yarn.lock'
